apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 846424179452.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 846424179452.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: 2b75d780
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
